### ISSUE TITLE
Code in AuxKernels for Magnetic field

### ISSUE THREAD

**Issue by mangerij** [stevenchurchill/armadillo#5]
\vec{B} =  _grad_\phi_M

See https://bitbucket.org/mesoscience/ferret/src/83329f692a494972cf62f5dbbd7538035eeec882/src/auxkernels/ExFieldAux.C?at=master&fileviewer=file-view-default

**Comment by mangerij** [comment]
@stevenchurchill can you make an input file that utilizes these AuxKernels and then visualize the vectors in ParaView?

**Comment by stevenchurchill** [comment]
I just made the input file and started to run it but I'm leaving right now.
Let me know if you see any problems with it and I'll fix them later tonight
or tomorrow.
